version: "3.8"

services:
  cafe-api:
    build: ./demo/cafe-api
    container_name: cafe-api
    ports:
      - "8080:8080"
    networks:
      - cafe-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - cafe-net
    depends_on:
      - cafe-api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - cafe-net
    depends_on:
      - prometheus

networks:
  cafe-net:
    driver: bridge
