apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: cafeteria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cafeteria
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'cafeteria-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['cafe-api-service:8080']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cafeteria
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus
